server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://106.14.180.252:3306/apisys?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: apisys
    password: apisys
  mvc:
    view:
      prefix: /
      suffix: .html
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password:
    jedis:
      pool:
        max-active: 5000
        max-idle: 5000
        min-idle: 0
        max-wait: 10000
    timeout: 1000

  mybatis:
  mapper-locations: classpath*:com/example/apimanage/dao/*.xml
  type-aliases-package: com.example.apimanage.dao



