server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apidb?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
mybatis:
  mapper-locations: classpath*:com/example/apimanage/dao/*.xml
  type-aliases-package: com.example.apimanage.dao
