server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://106.14.180.252:3306/apisys?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: apisys
    password: apisys
  mvc:
    view:
      prefix: /
      suffix: .html
mybatis:
  mapper-locations: classpath*:com/example/apimanage/dao/*.xml
  type-aliases-package: com.example.apimanage.dao


